{% set version = "2.14.1" %}

package:
  name: jansson
  version: {{ version }}

source:
  url: https://github.com/akheron/jansson/archive/v{{ version }}.tar.gz
  sha256: 979210eaffdffbcf54cfc34d047fccde13f21b529a381df26db871d886f729a4

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('jansson', max_pin='x') }}

requirements:
  build:
    - gnuconfig   # [unix]
    - automake  # [unix]
    - autoconf  # [unix]
    - libtool   # [unix]
    - make      # [unix]
    - cmake     # [win]
    - ninja     # [win]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:

test:
  commands:
    - test ! -f ${PREFIX}/lib/libjansson.a  # [unix]
    - test -f ${PREFIX}/lib/libjansson${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/akheron/jansson
  license: MIT
  license_file: LICENSE
  summary: Jansson is a C library for encoding, decoding and manipulating JSON data.

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
