{% set version = "2.14" %}

package:
  name: jansson
  version: {{ version }}

source:
  url: https://github.com/akheron/jansson/archive/v{{ version }}.tar.gz
  sha256: c739578bf6b764aa0752db9a2fdadcfe921c78f1228c7ec0bb47fa804c55d17b

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('jansson', max_pin='x') }}

requirements:
  build:
    - automake  # [not win]
    - autoconf  # [not win]
    - libtool   # [not win]
    - make      # [not win]
    - cmake     # [win]
    - ninja     # [win]
    - {{ compiler('c') }}
  host:

test:
  commands:
    - make check || { cat "${SRC_DIR}/test/test-suite.log"; exit 1; }
    - test ! -f ${PREFIX}/lib/libjansson.a  # [unix]
    - test -f ${PREFIX}/lib/libjansson${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/akheron/jansson
  license: MIT
  license_file: LICENSE
  summary: Jansson is a C library for encoding, decoding and manipulating JSON data.

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
