{% set version = "2.15.0" %}

package:
  name: jansson
  version: {{ version }}

source:
  url: https://github.com/akheron/jansson/archive/v{{ version }}.tar.gz
  sha256: 73ac12bbc62ff536e40c7a3e15ed007993c5ca4d23897de23f1906f891b5a4bb

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('jansson', max_pin='x') }}

requirements:
  build:
    - gnuconfig   # [unix]
    - automake  # [unix]
    - autoconf  # [unix]
    - libtool   # [unix]
    - make      # [unix]
    - cmake     # [win]
    - ninja     # [win]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:

test:
  commands:
    - test ! -f ${PREFIX}/lib/libjansson.a  # [unix]
    - test -f ${PREFIX}/lib/libjansson${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/akheron/jansson
  license: MIT
  license_file: LICENSE
  summary: Jansson is a C library for encoding, decoding and manipulating JSON data.

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
