# Jinja variables help maintain the recipe as you'll update the version only here.
{% set version = "2.12" %}

package:
    name: jansson
    version: {{ version }}

source:
    fn: jansson-{{ version }}.tar.gz
    url: http://www.digip.org/jansson/releases/jansson-{{ version }}.tar.gz
    sha1: bc2b107512cb7d65ef108a7fa560d6bf970c2a40

build:
    number: 1000

requirements:
    build:
        - cmake
        - {{ compiler('c') }}
    host:

test:
    commands:
        - test -f ${PREFIX}/lib/libjansson.a  # [unix]

about:
    home: https://github.com/akheron/jansson
    license: MIT
    license_file: LICENSE
    summary: 'Jansson is a C library for encoding, decoding and manipulating JSON data.'

extra:
    recipe-maintainers:
        - mariusvniekerk
